---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBX33r2viHMmg/7XdIgRUBhxXIXj0dFs2tq9qAerqHhkzv60Jk9aAngSBgoNcztyuoMUmioy+qnXQ/T0bgAJURAmjK9E6qBZxeb4MesmS5WxDc50m8tZa1p/hoEByiM9WljqC7rAvzNWtRrWj+Lp7p/KhTW0NcXRc/5QCny/cyhsCijbAWcHvBHZu+JB9S9WEWs7c+6CJy/H8ipUzLCUiAURuivIJ6Ny4OB08kZtQn4dtDvoAlDnvbc0UI4JxYqdnbTPYbeBc7fS8sNPP9HYeqdRSxVXT6yKHR6bmP1L9/auwSQmsmspMqwMjoDPMFwm7w8YKsZJZC+n8aeo2Q0hGFTwnl17iFK1Qg2RHtqb/G7bpGEE1vC8aGndBZ22JmSMhCuI18bQ5U3BrgD9wpOalA1A26BvrcAYpNf0snMdAV+zjAjLxrZGnqYzwhZA6LtBCzF8xOeRGEJvvMuyjr5Xar1mne0CUiDX6vcYIil6NNFZCjLqZNlkZ8GI1uHhWRxwq5OfbflRCv1ThXuPGXEJx56QnAf0zc0VSvYDi/lf6SwtT/pOz4mWMKee0wHXTkVej8V4qXPKFmMOTD5M6c2nfpo3OY26GIVeXmoHgMKDH2hI4ak+EqtJ5W+iPmPOmD3HEnfT8VpHRmJ1tnxCZKPWZ4pDMdX/qW9SymENOMY+2I87UDVvGmpsQqDUu9z2YSqmS0oOccSh6vLt7mI
    admin-user: AgCX3IbreOgo9F7XNAlsJO/7QYVEMiN4aYd9hHAWn3Gf9oZZzdAF5H6yGJMA0qhU+SzICZP+D9XVoedd1VhvaKkUCho5yr+dlk2/ZP1Prc6H9RUerxa40WDYTiTaf6r+9ilvyBUeVJ3BP1usTE6sndCa8jR5kqQcKMJVpsvl3iCrrA2ZXLnMWzn1VeCR++Uo0C7yWK5PAlpXyvFwyUVOB8xgPwWUYqGUzyebEG1vyFd4JE26qFAeFroLpBJeTGlKxWM1AOiGRNQNdq7cI7k3mFhBSbKgPswANyDDC4K/XrN+vo+N5dTRYBrUTC8ddy9hVefVo/7kRKF77oCeGvuXccGhk0O6nsHtqhNyZLF8dD/xP3WPWxQoltKw47lXhtY1ZWepi6lMx88C07TiIGbIfBKRdApJleXQIxDRmhkvNL3MBFayvjtIX97lZs35xfhtl6Z7j1ixl9pnmibXseJMEfONC/lmUzKmwdwX7foBhPrF867lbizeEm+iXmcsOIqi8iI2WrKnBIFuTWRNAuV3dLwRM6EtRr0LUjCfVhPAm+k9ezeveEwjHBusBmNQNNFz+OxZ7bJtb7WJFUGjqTLsV++C3PURbBbUwTHOnPTZ6uuXpVRtWelQxBLasQ3KFcWjRd/QTTkk4cnhnpsUSgEHA7p3j1PSqnuO/XucNOqSaBpB9C72RLo4oMVU2UhWDPPHCuyZhYYI7fK+
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
    type: Opaque
