---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: infra-system
spec:
  encryptedData:
    tunnel-token: AgAzk/3ERSzDj8tyiTylW443eF6X0/euHlhhktoYelZejgeDJnPnZhLsnTrqEw6LlqCwtWAMUDv1+s4LS+v9hiA7KuRmmeqO03jHqhPdxd8UqeOMo3Ml53FcvYhlJ/yAfCsB4ujJPeliCedFX2TmRzeoB8nJYJaUdleZ5+aMwn/JX3K1KMz4XnmYPMFGSoD/h7wNqSr8Zlhr6JMLvaCPhZ79IAJeGv9gosqGxRI7yIeApZgu27jpGvfbQTH0tjzbLMcKFLW/Gu5KWyQ4Hsztuv7vqxjWOcttHt5xbdWDj2GpNUtJZ+ajyZ9M/1OdoTn/zzR7KCGIoOIP6GEkT9/+6YosXSaUU1OfOkwRY3G/oqqwtUGZ1g+3YKpej6g+rggGo5vA/8PEdplXn/iTP6IlaPu5M4y/I/oC0ogbMVR/3SvwCq1qgGYZgt1tFjDoyTcThMoHoqSDhOwKz2OmQFe2OOQRH04jW9GIT80ule+RPf7QhcscO4n0TG+YyPOPL+KoPmK8CRvS4sqNF7gO5pB/IgJP5a7KFb3NEO1vf80j/6Huw174quW5Eriw8MQXJLWBrc1AMU4gBnywy8vQ2WfB1yvuL1f7kItodgrQs04t83k3F6hNrvuOY4iNH321RJrPTzA2+XDPOj2vfaZnhFFLiA/f4h/LrrgW90zmMBUj8+LOn+XpSJBZ2Xk0P9YpR1UQxdM/wtBS4R6q1D8fhb1XhjSHd3bQIQz6a2k/d2EjG9Ync6WkYZpIrfbfW0fUTcCkhOOvJAnTVS7L/0UrHQ8bWQ6YyNusej8wtDatGqHD7ebtiP5RdIrKk10rhqlW6gXQSGRPa5wo/8hsTOagk/JbAhRO+LuVkNGPEwxtyqywrhPyMUM79UcXzsSDo8uvy+78hc63c11uvKKBbz37G1gKTGw1o0r7pS7ql21DEVx+wRTZN6Tvbjmn8QlK
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: infra-system
    type: Opaque
