---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAdD6LldGHVJniO8Xqrp051MQC5lT03IJTDJBsZeU+6VrplmEPwHXBZ2Q/1prLpfPG53t39lGIEonTPXQ9zfJ6df0lIPe61uhGZDLkxQVJA9PfxM7hVIfDIdMk2rtA9wU/EHsFBEo/gnLHy5mIcn2FBvrTMX+nNbP23j+IvGJ8Lvx6A/GtWcpjkzITqrWSSLFijP2Ox8EnWSsUfd+7AKF33kB1pq7cV+uo99ko+Q5kQ1ZuxlgUJ+lusIGAuawHYFYCCoXXhROeYmP59g1tmYzoMc8tMBEjn/aaTi12jL+hLj8VAMwhiAZ1dR7PsjXVa3RDv9zKLbRaPwxbQRKK+7REhRIaml2/9UFhOtwvGYtIXdjXdvclFq668AG/A7BUuiDvsOttn2q5P1GK86dCQMgghn0OkdsdAHWRx2ikDceMAy6hmGZaq6NxxugAerleWQAcD0CGRE7twP8wFTdtZfjhqXCaYcXrZ4ZFqH2iGwRu4D4xmb3krlxsTGfuH0fZKA4pTFNx+BwffAgDGG6vaGn8EtJble/zUSEIFtEirOjTGjEEu/UUDvsJjH5oEtTRnk5EuZze6lrDPYqUwN/t3/pyevPnqF9eo0BP+79/jWSZluKtDrXpyFgopb7P97iOan6pyT0OhFXhniDv4cwO4HHkDr0rcu1M6VR/ezuaEj/9hzks+IxUwLjujUajDA83gTjN/WEKW2IjmyQ==
    admin-user: AgAstFLVhofOfZHoNGHVpcAesnYS4rb47lYPqcVGVQHl3+dYXD1kz/j7Tl3nOXZHgDHkly05U15kxs4zyNfL2oOxjyUAs2+y37J71dmrCooyiQT8DEo0Wyj+Xt8N4lkGcXk2XwwsMq7GnhDqwoOwSV6M5a5PNFR8HR4x9csnA3UaTdJwQMJklSWso0Ni1EIfG4kehQ03WDtUwoxFQUayLCqY9QmhVMRQ9cJB/OsQ4JDzjvRsJHCVWeOrxdEMhsRojv8UjMgbRT4R4ifMvxnCgVIxV/AMKloH2eLGrKJddU0VBcX2TLQya1fporb9PmQ3uDPrMHmWYRu37419JnL5QFFyNfG2YckhGJvBLVJZFrCLUhswARiqKDeTIz9wcCZI12u5RonXqaWRLhxBGa2rPw2HVr65LPc1zYX9ZWsNxdSMZUUpk4D684ayNPWwOjl66JQyv9MtVHTD55V88Iw6z7Q71khF7U6p5pK5uWmWGCsYHhLCCpWBk4ffrR1WqICgAjXvy3k+Q+UL1yJatjrPOil06IesvX8hPAwxDC9Y/dvzJH+KL5glubE9Me6qOusB1yhsF6mWJZUlX8kdEfmkRlCL09RUna/FSaLdXPNJqdRFPjeI3cSWqzwBOqj3wV0z56QxKvzYoPWWSA4yyvOWDftH8YREcQ2ffOny4ny1Znf0oTXzKvh+ZV++gPkoTEm5NAMUT4f1Hw==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
    type: Opaque
