---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC8Q8qVjL22nwxm7TrhaF146lPlkx9tAcxQCt/h7fUxOJiQg2CCmw4wgvZ9eh87eySu4JvefijkO2r1HH+l2LulyAvXxs2cpu0nS8w8yHgLJcY+KN2maVWpJGmWLVrAIKOY3/rsFoEp49My5JrOxYZeYYGYTmIw7mXfCa5qYBVhUBqFPe8KHd2YUAEryUnnJe/FLPuGUrOQA0d0txw6m5iGRlz6MeIAAhofJx+H86RSFtBbV5Fg/wyP3sQnLFS3HT2jk1rIl90IR6dP6azRvKLQWQCz+sA8Z1PRKZHEYwmysk7aweuPJqF5Rz56g/535TmhZFHn3dpVyaH0yoxkNguAmXtlgdeoElX7t6y9o15XQREPBG+L5drbu2YBoCSbQg1eTYVwrqssw12qk+fGxrOH0JgRbj7XCClGo2qe6kmZhZYUO4+gUWM8FBqPRLnlTU64TW4hwU/axrhOK6F4I+qmN6ybbThwen8wtev7cuL+TS7WqtfMYmehRq40k4MBnAjwQn/8+fM3V9GMkTk7CbJgBVRNEdqNdqV5bJCMZE89syrcj6Netevw3FP/BIPZ9VtbvEbsQZevvbLOb3zqStdBPOk/cArgxDlYaD7O+c5i/9O7/HvWGCW8TPdIUaBMj8v3ioVKol0UnJKpPu9Y63PEBwB8A1ovbxsVTJmFyQVHtHPMCrntEyvHOKFhdwezrPStJB/k0rJnsA==
    admin-user: AgCZDWvbYivH/bXcB7YH+7uT6O0B/dxpaLidSjt5U0Go6t+sueK4AxFLW7uVOLx84nSz4hTjCiy6TMO+WMLqkY9SQIB3BAQGjBbd5m1fCn6MIvDGztlgOL6SS33Vza9WuGUqnx7PBz97QJK86wXeVWbkq5q5BTUgVfbG+Hvrd7rF5yMoNSryRv+mj2mZIuUxAH6g1V9xDtZ8k0lcEtz9d1sFvAPgmZf314IXbcPoqrmGq9v4VzetyI8tZAvQ8sy7jg+S+Wg0+tgWRDGiq4NGoSXElT6krF52ZF66YeJfziFOwCHIMnoKBk8aZBDdvAhAdKn2XH5gNbYhekATV35pMalnPC49UwdzYSfzAHusvMPCsZDcvcxPvWuKZVe/1aO4FhmZRW+7NKfL0r2v9wBKOOGgEZ5W3rXIJHuCd49Fsf+NJ15VPO+2G3bFesKQz9YHr3Ic7/2BG9S3Rc3fIiYaLqF1ea5q+Zi6r6E6oxBldd8SRsYMMlObeZ6rEW+Xu9p+V6s/+STKBo5XdXsCc+qa9D9fBDV6zy69+EuuV27AcxXQOJIfIAhnD6nrd5fUSymS6fWE9spGRNrMA6WRc9IetR2Fj4Mh/VOxa7n203Ig8iA5SgdWC2sQ66+1y4kqsyfcZm1IgG1N+fbyr9VLIPivZbmIyatPKVKr7uzEUCYa/nsSHEBVBoSCH8pSs7J5sqSogpMPzj+PhQ==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
    type: Opaque
