---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC0wC8lPgVh9iPqaF/XlRmOyhIrfkh9uIga2t7IyxoA5p1ejuYGyI4vCXwu8ikMKVV8UgCV5P6at/PAhZBWeHSNSmfD23HS8iBMJ9/iAkiHxO64VxEznFhvy1L5tD0BJUScfrDbgi72GHZmHBN1XCJJWo3ue8deq7n2rJKymXu99yiibld6eDI7Ngst2SIlRB0u2JS3FzSHYcZr8yCY9khKHbovllaHdtOcBLTNlPh9pP2PF7Hjv2aS1nonKCKhVKtI+jMnnOxO8oEZniuxXmocwUjKiEKUnwJ08iP16xJzcCkusV75lvjqLYEKCfpFc1HLN489suoLBsO6CshWaDD1eT9KlCJr3DbfzrdHqpUz+R7Lwpi677wP6OFL5af2e39FBGiz5s27yKA+WcrWdIP31US9eRAdSqzRJjiGLvMC3zdtCvlDmaVCUWXti3c36dFrmGsFTMMjpYf34BNpQ7Flshh7C6KpHUx58mw/bT2Gb0T95bVSxHhUNhDCPBcJjjd0WZSoVhbc62VCTOhN5VpnK2ZkDmarU4eSUOwQfnTzy8aDXQM/ZrMp2vV6HLHHTyhu3j4Fmy4XS3gwpOlgZHyOsuif3FALYBSgEg8ebvp3dLPlZRTbE71piY08qLNgNPiOcHAzGQHf+oMiEun1NcEFhtIqVNEoh51/VD2ckzIZaLZKAPm6JmqyrqmozS8ZNwOHV7Ee0tXSNw==
    admin-user: AgBHSn/ZhiwJ3U51vx33rDbqBT0+mrhag1aFipjG93+1juVZMmD8ONrcVORsteyY0FaU85fQk7kOvuqJd6+HCFsbsPOYDIV31BqN4a2IU/QjG9+rA/TlhVcgn5dowQ3TrJCjpWJpSV461o+/SOnUWWQBDY2TLkQVfnnSTJEetYGxqSmEAiqlpg6scqGGUcfUPMLaCb8+qTkUF5/1SJiZBG73EkKkcRO2+uCWdFAm2NW2ETOSj/AZF78yKNPqeQI9tYGomhMA+xyq6FubrrGvacpOxTiETp6soRkbWuIGQ2nVX5h3yg44ZXPpFq+7kiuo2UFrJ6rB5e86BhtrAUJZ/E9a+XW8UpyDjsbOH6oSfA8Jmmq+tXXAABFOO5W1mcT+IyrJgeIl2Ca49FwaR158sqJ6dmVOGd7SKo+dXDnJI+XFOMOhyXM9XEhGUgtAf0FHkP4pXb1CBH3wejvbjwahxuP1QBMzceVhwa35WecLGEGtl80marWqLSDpfAEfzFG8gFHPoZsli4fNDG1egAv0pLDuAasInfiBBDyZ/h+CJNlNJ5AMSOyMpjHC7v8bGjDa/tgArArqGZar2DBS8q+7SiH4fSB5T5aRzQI06HX6WgbjPmcOCA2Tp49k4wQcgZfbtMMTqSVqO7KHhwaNQWwM6fkoxMGeZf2vIbBxT7m6V4+lWvSOFGyA/gYMkeufTx8718YgdZxj2w==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
    type: Opaque
