---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: infra-system
spec:
  encryptedData:
    tunnel-token: AgAE3fhG1LuOf7SfpnLE5MmgIVJlo+ytte07Njdqa+ow4xPpyO9qTOUidg+Ilyab8HiJvZmaAiI74Zr4nRQEznwPxCj5rBzWSyloyjMJLpSFLp0XqUl6eatfuUzT6rpL8+qtiekQFjTHCqvGDXCbWZtLKpUgRefNojkXrLRnSAmMEOIi0RHnPY7LS46UZUpCrtV3BgkKyoWVVo5DGj7QJ6mk7NocxNTDk0+eK1X+NiVor0WBqoTxBJuk1KVKSf2j03Jl7yBlVsz5KTTb2HPh3tKfEZQJP8zGOX3slVTeqO+PRyew6EwA4G1g9pqcGcwDQK0RRgT23EpEcsT9zjw4TCsEEo5TObM6XsfYY4OVsTZHDDieDykABTBXieZqVslVETAdS8hPQnWEuQwPuioYLXce57Ccffa59nY5ViAAb5FdzT3VxFnI6i2BgTIpXQmrByou9sLgX8DzzIaez3sLDwaE9ixYL1XYeHKqfTS0/XlGigZL2LP6TCBu1m58iKywkgtyP9/fIsXdvuXbLWyPDdmm7a9Gtwi2WIO2oKP+mYc1jk59REEsrKB9/WiAgEkEGLV9152qA7S+2GAmOxOGP1ND9/sgQME+ED0A0Rnk7MLe92R5QZ4YKNUghJAXmdvv63vqbNsSIboB0/kPhKpKiCVvoLuDiwu8M/jaFg1lG9rK9R228tmE8K844drZzSyOsnDX8nETJQsejcifnsTGMVQVwJsR8TdKR1oebKXTT06DdCLg+2mHsXsSD5Jc3i/oblJgkiaL9MF+6f1O0uxDjPYr8P4veQIex6row9vNCIjZwc43L4x92WDyPvLJp7fcf6y3vALx0SwAJigYE7dBDiRg+0YxPvbzq8wfF3vAwfEoA4V9UPbJsvXgk7WGLvKkHe97jCLJSTUWO286C05q5Gih1VGwtJojEajyxF/dLmVtMhjwkRBwx82F
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: infra-system
    type: Opaque
