---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgARM/RyKo9VBqK0ZtWSX6aPNfxbGm4Lpg4uyhh5x5URwYtnJ5zV8DnKF5mjYNij/Ug7XKfLMtnwagM5+mZz+iOJqqbUlHhKaoQWwptbYpXpTncdACrqi6Mymj2+W4J/V0zPCiIO7h74dgWEWLI10MSZGnGAmYktwNiGvBzYEr0N2ET55TRGpZofpd2HtsNlZUiHB0O+BbiVlBAVPDPQul2USIgYNY06J8OQXOm/NlcAn0S7XfZkL1TDh9TduppzsrWwDM+s1YSPo7h3GCI02QvJ1Yloa8BLRtZ56h3sDFVkkXWlOZxXPbYF1TL9pLR/QxG5M+3dNmptr55yp5CybCVegb8krbdfpVuTFVGpptZQpguWRjEayJ2Oi0CIMcHYIvnCXDIOYXENP2UvJIz4ll7zbVmKz3XSz0y3OW/+N+vGh2WbtYws3gTr3QNNzq4yLCu49U+GG/BRr420WRmi0ooKvA3/voK2FYiYjgLKtYWZ5vUswRz07l2J/xOdhd7f8FvhWxsZfcd3ACSFsJQ6GsLpsQIlF+1/FGedj5WC7ouykBzeKXGrdemkeht5/VMzy2GfjGicpBcPsQvvjH8onRRUzNwVkFDueGwrSgWUK1l0avT57kwv2P5AoL6P3lSuoQDU10/dj2y336U2xIRrrGz2hFqJ7QRPs+0RpVfT3gEDvLwPcuRswhOwPLNG4S7k0Ie4wgLWZRx2Mw==
    admin-user: AgCHfPjMpRdzZKixwZV5ZdrV2K0c0nRzWXNEwBAwzIv3t3KE+yozidYFbWBgJU5hD8oCQCCU8yfMgiqiSCGZ8VeUCDoOpsKOoe5H66//TYqZ19pNhZeQasypbf1Cn5tF0FVlLGGoj19teEGuqjnVhNSCjAFm2wCz4xlS4acwwSDtOhRUrvMjYJ3D4flyBUXwBuhTXNnX2diOYjAbJJ0XTknbKLMk88HFZ91zAL0jzhujmTd5xwfJBDSCZJ+T1elf4lyfxTohLgUoXbGZaGFPL4ty+YED8ystRu+kJt4jHea8lLm7Qq9eV4GOVf/YJiMgVBzDBmF/eEJXBAMJtPykKh9/AuOI+IK8t9oLCTPx4qXY4wbqJLlIw1t39A2++/MoJXEEKxzwYf4dqt36TjnpWGBb4vFcWV4anFpHFfadY4qUfvgLhyDcJiVQcZDBaYNwDtp2sPvrSlz7ySEN0TcHoryptp3URy6y3ii850oP2wqIHtieAqHOl/O5W+91ObhZlYP/QTh8I+FuXI1oLz4O3zoozAkW6i7utFEYE0ex8lSsyx4jP7YGLve6RR4B92aq5GiSA/ecUJpA/SNlkBKY3R7KAOZJvRLrMGcm/KW9jb2+xUhslLdASdDFGdFd2ftgVZ+NvkhQ3P2zTRknLKEupcxJws+pDikas7PJJ+jqrVi0RUvqol0t1Hi+nwwncI385pWi9HhExNN1
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
    type: Opaque
