---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAsp11qTCFfPgjK2gaEMcFH59jNIKVI0TbM4Xv1fptSbC9OrNRPEwREbjdmR65imWFT47r55+1Z53/9XuyrJvDbSs3oOYFWZsr1JsPpV7DxsH1ejylWiDGkiokERbibMxbN++LxNheEOzElWE3Vp6eB9r0QJBq9xkmAliwIry4Rbah9ArrzkS5O5voorGaUoVxocPm4Trhfi12xBFc4/VRNUVxu+ZlHHHMKOwzj7uBC1CVVBuDi+CvcrHNCS0nhu50UVFxhy69b/+M7oSOL3MQfOy/UupVrR1zofS1AEWOScxoG1xudFeA+GorQIeDRUFdv+PMf9t/HyOCFQu0tT5CE3SUonGFK/wmTnJo+yqUXM4y1JFkeB+LYbS5LYDML5QdlY4SNMoO2TbF/O8HauyFdaOz6lHMyRbhGMvxxkBiQ2ZZ1SZx80ewp6BViJTFb4ZtiBzE9pZdUKTekToMbQcx+QCpt278WI8f4FeMy4DdwiEzS0qzSlZTMry7q1Rfj3gqbKrTAs/1X2aWkEF74GhjWSKX9xZ6xerwkybdpbwo0evvDytfUeWvN5iw3qW+YUPdcSYYOXFOqYVHm3MIn5o7P40IaVKiMDNqtJunwoYVvwptisqZIN7pdomveMGq36Z695C7/HO/0u/vTzJWs3cDeqATYTih4me15S0/d9v3IzSfkkxK6kRbDKePKDr2S8Fzh4iXiq/erKg==
    admin-user: AgBuxg2v/lVouWfwcbG3eq3hN5ZCaajp3MgHNCk2XKZnDddonR4nZIUs3NTYoeBbz5lve/yIR2vNgVuw6Nv5vCAgGu5mCvJCvOIZobzE0X+hCg4wDnRTHi72MJXmhycahUQxYgRZuOBWQFe3H4CcFCwaHfR/VYrZJ8XHtDZIGXnvTwevO9TnVd3m+slR/IgYJvUfGX6iCCCzU2FTGh6TgS5d1rs4Yjgdbep61wGKLlshiB6UYFFRteUpKoeErBcilLfk5DJ8oGcPEbkOeckANSwBVdcRIf1cYB/cL5u0+vWQ4ktkj/IiRLFfSLT3GiQJzLuNEXHXBJbqsDim6jD8zRPXmlwqD/s33urOjXLZGve/Qt89SPUaWJyT7MHxPltIRUjKTrwLZXd0DCQBoB87LhIi0LFWz7dZRd1qi/GXPdNiGRUO6q0hBaA1tOK+kkxRCKKWc0hdP+58l3IIaJTx1i5SXl6eCQhcGoA4wkpHQgdabxAGMVAeSN7/Gq7TcwSXgi4iJQlHXLWd86y/OaK56q3EeI5F9b6czLmGcJj7wOhJ2f+8H9HMC00nXbfFDq5pyGxV8Gy8rsCjTqz5zdYUeX7j4dw6dzzYSyrTGSaA23N54nqXw88t/TQVRXuyo1g5BAT1eW085hPYUWQZYWysnfUiNtpGE6W0KLuTpOlSBEuOHSYXvUX26iPdn2vPA7km/21mPjFt
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
    type: Opaque
