---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCMimRXpMFPa4ibsi21B3JrT0pj+kd4BBPNPdpPKacVHOHUcnv0zen8g2yHiryAVFX9iNWw4BohI/XzBU13gpc+mdmxAlFK/K0lKGxoCvEI9fNq06buobAP/BvNuODxqIQ4mGmTg5ecuyvqojCVWcc6Xjp5tR0zwy9NZVKT+5wtgDjqKvpFI4xwcdT03Fv9vDUOxM9HcoTBHBB2JQEzlGo70WnM34Z5gHu6TtzbHwV0bQ3aLTeu73kzyAnnp04VCIcQmhzBIopeLox6vmlACiLoJNjJBsOweGQmDWkSxKdFsMd9wTGWweFLEkhe1TkcoNGUzoqvKyJn54+6NQXKI6+da+W5JLOdXX9+qHK8A7dYu49TRouB1ZfDNknql2z+wVZ8ndoXulJBKXqBt9xrMtQksdQ0hEnPJE9qv4K20fSD4fx7EWdwhbNtsfNunu3vL6iIFO+1rV9Qu3UbHSlJYyU53JXC0t4rQzmm0ckTgjTBFELKdR1f9z/X1n/oYQU4V0UOmZDGMRXEzPp6d0sjxNvRRjF08xHTEQKPE8/KyD5K0Y5SxMRqVYvDaW9Ltj83vJbdsUp7B0vBX25jtciE1L/stD5JM1FyzRAfEqLt0qDDijbKjzFRMLQcD/ybIsthR66hD+bu4IIi8PDTFMxrgBrsyGafc8HXXwUbN+XcmPjkpO2kfiCyAwMhcjR9SDlIYe565xcsA8q1/Mn+
    admin-user: AgBSBowW6C/wPIbCQOJ3jbat/jXrpcH4KYNuAt8bPmcNZnJJPgWVGRi5XruXmclL7Xno9gLO1TzO6c23YQhb8ejdQ5lU4RBmo5z1mcVWU8SsYm/tEZdG9YACRIYyaqW3Lm6/tbR/9F3/2G5PMmWxbeLBvOM5QUHLeMb2XEClC7HsMcaumk7QYH7fnGhSLmhLEDfRkVSJHYxfzi+7FmKtfNPZA6TzLjYFO06hFdaAxTQrI9n1pmKQeI4hwTDsIpQD6OK5LEETaLWZJaZUaB6cFacg7VEKSix1hi8Dwu2s4YmZ2vUTyjkNvqCfUfcSW3C4LfYvr85RHI37vzpmrU0VX6B5FaoXNo3hIAxuJirKIe2ZvAhej66hRlizvC6BEDECeD0XwqkUE255HDFvOgBtlmcLj+BgfHvFYxRnCvDeBZeVs8FZNm3SsVnX+EV7glrkDgDRDjRcc8p+EqksxeLEryGMM5QG8a+7yWVQHaLoYRabjZvU0Ig/dHhZK4N1YhX81MUG+jvXQOZ2jpucfSF9DfqtoyPlqOkCBY4fkj4eJfYKY1qkwyx0EUVN4HlJGzbj+166H363KTW/N/KVOma4rje5Ml5+7XvKPtxIGXtQZ7hRc9NSKvVgxpxC1XPzQ0xo8h+VLdEaAEjc8XEBUf+jjEgb9J/5dBdbsbDZa2xnxctGWNjekPSV35CsBbwf5RIDyRQt702MCJlj
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
    type: Opaque
