---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCv+/+PZWav05W6TFb9aRXaLsorddx8VAAnj5UkpI9ScRDW3b+z4mbDQK76IeK2janjIqQM7jlmlQZNyfN+eNWIleHnBdf0DtTX5Aml2X2dPpavAccf4AandmFpMEN3+cUJEEVzenHJvoa9xQd4FjDJG6V/iLcScqWVy3tUxd12DVy0z6fs2jr8mWuCCVC7Mg6K4gRCT+XqFK/x6CVHfyUSvqOv0v0Y1sx4I5vFSqpoPXFbM56WcYqonCPHkNLKi9bXRRwYqsrNXOHDOeWkFLLTTevhcXlPzyL04QgBBLgTI8Yw8mynImhtIE/XiGvp079KgQxLw9Srz6Uv+8gI7EEgc0ngfAAfdZKTyJil3K18inZcgISvMIw2rjQ/lOaZ1dzP91xnreIaX63oFZzIdUFUL1sQNppafqQOvrPnJI2s+SlrtNT2N1qvQ2Ml9o0x2/MZAC/TkqdxWNQWmHxXQZ69y/t5awE2g0MwU8jAnfVVKIu+IEiaAGevWm8ldf6Y8f+5uO7QyxSR9pqIECCdu4c1sGirCMj/UadY+7ySRB2RmhZ+eedwhwFe0KFEdUsCNeBMN+KeoaMFkayqqF8FNyBRcE7HsZmwGu5Nzr0La1WGufres+TFrTgmU4X4ymmgqz0vRjOdT1iYBgOPXyqw1Y82lu+PxC1eH6uSgbZjPfbmPJnnTH4FpllUV4vTurJbF5e/CnF8GSg3nQ==
    admin-user: AgCS50La3zaxqp13WxhTgLrqjAy0U2NVWiqr8sHje1o3DrUsPQ1HPKZFP+jlmc2gP4kGnjjIx6K9YrPYWg8K/wOE5mzACX+SN92hEs7HLhmemWV6S+NN8Qsauy4xKFZPMz1wVuGzY9K+9Ybe+6aKKIMuCErGfjEeJSVZBHw7xPFgHAy/pb8jZTHJq/VlwnUU3y/ha5/TbufSa52iJQk9w7AlqMzgpdSufN9i2yjBmsIVkcTBSHu3Q8/nClAmlw39bZ0jqVkn3iQ1mWhyQyRbuesvRkNXZgQrTpZirisvJodSP15dCW3W5OTpG7ahQkZ9+ehYo+l6h6/6jBbCSzPUWfvRzGRAMMzwXASWNIrZk5HUYyqfdAwvVGCmB7NFXZIEGZc2q4IH2kuFo+gdJ/qRGYRFtGea6SggBMb67rkTF/yau9jiepurb2s4imaIsYjRD00mOxFmffgRhS+P2D6aL83ZH8bBS57zjquBnfax295zd+yZDwX9gDOdtZXjQcMClqMy0OJMymoL+nVqJUDcAO1xL4skzLTDOeK1jWdOUfaR2VIfO8oJrdIjysVDDn/89bn79u+5gd/v/Ugq1NQqUAl0iqUHysJsHtADnu8PExlkKShXh3cYGqwaR3q9jHZnbFy6GboRraNT1gyEpgwCxwowybwJw6PPBYHYxtbjIFB8idUyx0eItzeBeqoaI7Y6VfeoCxAzhQ==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
    type: Opaque
