apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oracle-free
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/hankchi12345/app-manifests.git
      targetRevision: HEAD
      path: oracle-free
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
