---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: infra-system
spec:
  encryptedData:
    tunnel-token: AgCIpvKR3yNHUlTxPk64VA1m7v2wxUSxNxjBifBJ2VYxPpdnmWYp3lBLr3KteFUMch37VBLCN/wjU+Pk1YfsQCUAlu9x4YHED/t2CGGrDQ23A1/qqVerjhc8EjM2YNF+jAdsd3zUb74RiU+UFEpYxF0VPBY8/Rm8rH5nD7OiQIXC6xAGAqHiZW6s4llqLvqlZkxhHrInaKVJ2J6SKqglwJqstxJTykN+H/CYYOZIRMj39DKlhKmC1/ZtKXJPHOuuzBvpBBqQzTk43A9xKNiUr+m430KG1MAbniWSh0WcgAcPHgTKNxYdHrUz2WanIi9iVxCM2XDmUXhN3bhNcOnEfXgfrV9ehCAWny8WG05oJ4SzqFO5340Rw1pj+RoE+8sHyDt9g10uOKD07O7r2UVGOutX6lrjhbJkuvzILRnJc9/vQK0AeLRgoIl52BJ477IlqHVOUWcPClbkfEOljVCR/orrqnTRkMOSFTeesgoDZ2zWUH2KkmkLcZjTARuO/7ad2CR33i/JHd7Y+jdNPElhflxR7SEWSJgDUIFwpqhXd1Y+Nhsd5jGULRmZz+lmaE0bsHxM9UFWM2hi4nZTMMtJLBbquvHwAhgQG+mgQWyZ4xttiRnQB0MjYSfNlS/MfYSQbBzRZFY8iZQcLYY4DBgrtg2UXzpOkt7pmLCi3hF5kZBOnaMNESbBseKlbubBBUwNcmTQqtCky74bTSywnDVEQ5QERDb82YkHGE6/VpvN87WugX7NkgEjCLp5ujuG8l0d/tGvTgR4vqqIcweO72XoWQ0ZhPsHZ0JBWzDUJjTOprjgs3w6MwVDgZhJRppwgtZmcAhdFUzy22zpyuxw/YQyIukNmCxiLQ6yPxQ1416AUFcK4dv9koWkCoutxybX93rYQ9UeQQbxP8Fu4yLXbHhnU8wKz/oo70XfGn8vg/YeiaruCHRnqwLltarw
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: infra-system
    type: Opaque
