---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: infra-system
spec:
  encryptedData:
    tunnel-token: AgCXrM04KC4aMPs4kBftpsqRM4jbiOztmPimaPmpibpgKzqA9jW6a4+BC2Wpd3Y6p28qph5kGRsFQmUdEegI04HuDTaXbHillpp/5IiOX3kd9N7Wt4o8z4D4wIvM0BP+hZ2LDnirj9SVrilkpY/0+ceyu83U/bwXYHCdMu7ks/wfgnJxJalEHU7poRMeaikWn6bRMVFZiOcNMLe3IAu34/Iz9mEeZl8yCPKAlaT1Y24V0fVjVSLd09n8FatbPyxMVYmseknLHIyKwf8VPBu2Svg5tYCIuXQlQySkUasfLRilSGoSm75Trh5lJmkqtqRsZUEsMyRZ6HZqJtrkWIi2IJ7zhLFfSNIiTaLaIwev7+iiHotp7e47FeZLceaT6S3RqQVza7kw6DZBOnPPEbZFBY5TXGOb9ZsAyYSyuy7BANqwSizFyhXMLM3Eni76AZI9G0VfbDiZjpeNIFw/PnC1ZxduC1mMAupCNy2Wpkn7acZmDZryU5DG+6tNCru17jCqqtjMxQenTsBOOxtn9W4jE4Xx89EuxtT5vyShnxTu1znpzOeOFMwsj7NyIR5sxE05pnlA1/SbIUsr4L7HVGTUt3P94XQXjqVJtNQejPeIfY7KqCFEg0eumW8GBP4M/oxUues0Lklza4544Wgyo0/1Tkhoet/GHcu/9GsTvZN1TzzqpJB+GPOt4MSKiUH0MW2ENAjEH9NaBWw6sl5rtaaW/1w/Z+ptxMch1kw8TI125vVkIjmKeoszIheSX7Yi6NT5wF4NxPr+3XNGQbcdRnI4OPrGgR/sZ7w1z5r40QtVePYaAN8YTzcm7UBd6yC/QKneCV/7pclbqxOk9oOk7h07lRKXcNN48Khw4iTsMJdE7J/AjvY6aMkglVw8IGHnDm6roKaP0V/xfNnj4w+BxHmgNHuHY0pqofr1jtxXqQzUvTMIqnde6x9svSx8
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: infra-system
    type: Opaque
