---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: infra-system
spec:
  encryptedData:
    tunnel-token: AgCXEdcHSEypRu6PpmjzCGYdP15008IyRsrjTk/xGERrZVI9HfThBH0lgFKK0qp1J9c5GKCLRHjVKLC3mwBQaFIymXbBQocrorublNQcIZc31Q3xOF5PuRmzQ8GY7w36daMd9c2nehXVgyUvgRwDyFoZUwm266qfjc2fHiLveZNleptTwgOgqrBHFPCo1a+OlIvkruNi8/AUpNW0E9w49Ui7AdeHPw28jb3E4bxtDa3UHjXwqzKcdUu/FaqhEar4q357Le623BOc+BskErSPsGmU4kjFjelfB3sRdP0A9/dha9o8Bk75LyqD0hocbwtia58Dkh/VNxZFR/IaHpUh2UNLsgl2W+uZaMyqxavU2iDZXlAO6EAcmTwcJUIEPBzOI3D4GYP+rJWmhqdVTNMDUEnyBPlbxEvFDppy7XqbdpQuS9L0XbSYjFQTRh4+yy8h6e1peKjm07lqpZOiMkswZ7JUUOogYGF2p1ZXSY4DnaXX+yVPZBhUz8hfL+OvhXNm1vgNkfciwvXuylU3zcjC/SsMJptfQcHn9g1Mm0zcO2tHFi3rS6NFixJ8rNwQ05uMczN6prOMAU3vaRpdwr8fjjeUWCbZTV159zsAYDz3G4OWjYGu99cD6d3/nECRmkQpsWzgyawub8+AnnAn1ioOuwGABkQE1eOvXLHZlwmII6ewjw/fg6F4tHNSwh2HQvFYgyMnxzLSbsCZscxnAokysQIv6SFobmyaFPHRwMMsrzKmRFpEi7fbI1Ci5HPmUnjb5bUbRxQMllkdPqoMULc7Xq8COXCm+0g5kE35FvGOGEQGPLDD0QJWudjawKXqaWwoZHV7vqaF/FNtFLfdQ3Eb/6lQz2OCRya0r5R4h6HcfWwaztW4BRYfEYL2crurM0gL2HtULlZ7SrPimwMnhIXpvTFk+OOdSpl46AKWVFwFFedeE0hAy8LZatuW
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: infra-system
    type: Opaque
