---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: infra-system
spec:
  encryptedData:
    tunnel-token: AgBWA60xlX/vm6y9/XSjDsFuukl6B0sgGsD64V0LT74skdfQx4nl2Zs+7NP0VFrxi9WhVopNwoSzHaciKgggQ8rH/STtZr9J8EMypq3BfJlR/v96+teXwtJb5SSfUp/qJV1WgaOBE+vYqFVg/7dz3kvmNyaQM3rlHX067PKc316s+1oYPFvhIj9c6NJ0U9RmXzlySpVSnvmBT0AN6gt3pE3x/iUx+1vVIFhys7pmwYEGg4bcE0Hjp/3fFRmKvVlwDd1uJItvxY2M9gh3K/AQombE0p1Is8VvssBU5K1DVIzObXIS9wHkp9jev/xzYX5d230Pan/uDyWSKTvAGPPLYQwCqn1sxw13IN/59NEcLtk3BR4OGC7L0tpMrHAXkyVtycxPHKfTy5rMrWWvXmP4ie5ciSsjoiODzTFrKmIA21EZHbra7V+Wr+rqaocQ0LoSnE7GdhQEQaBlnYqiyv0ChwacorfRt7xarkE1X1NSnGkSQlPx07Y3MLqXZa3LdGtEuJ3wb5Pr1mBtAwpEPeBpiJsY8B132WkiJLsfPWD07rmPCTn5Nkp9MnyTeudpyn2KeJkWRG4p2+Dy2bcNhdO0nqE0EM6jX3N8s9B9cm6y75eWr7ihfayZ/Tw8EgFZrsImWGoqB4yJq54ZYoG/v8DhYSHT3/Mdv+4YUtfljcmwxgi/TzTR3GmZzYXkrV9Af2FTE7MinalVknNNVqPDx9yPzNU0QtxFtEgPAcWkWuc+GDYi7i6nM2mI8FKcZUiBv7i7/uT701/xqPwe/gCaucUM755LDyZ7xNLnfTzdvdlryxaCR0+AaIiKsTaxbOHI++q3CgoEkVjVfXMgzcjHlpTCp5mVX84UCfG8BEIgnU7DJTwvBDAVXfsvsw6ortMF/J3jpUWvyywT4rTyTUJWK+37wfJpFC6w6qEafjrcH6302mFxNGS/bhgsTHnE
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: infra-system
    type: Opaque
