---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCptumUCinT2A4yPJbzHQ7ogt3D2O+sjT4z9nTMAOEU2PUcOTUAt8EexG5Lsxbh/Qw+rMbQ+dY2L4LjmE9vJReSfgetdMK4r95IiHJPkxaj8VNt9cD4Mpotg72jVOdKlTn+KMg8BfjZqclrLHj9/+IHqNmyziy9qYipaVE2/6POaSw0rQ3jE9EFrOSQuV3X7BE4LcyZOPPWN45ssFL+DSa4YMIWK5rX4uyb1nCxhvqtVkPaPjPkWkFgmC8khbDVEhLgL+Xar0f1lrsKpnAjOADE686Y/lnZdQSj+dV0UCSuE8ocu1Y/MC+6hWCzK+qURwK2J9AcI0jPJGtD34ReEgOkZ1xf4CEG92dXDNWPvkgyaF+JhvpwGOZaq1Y3nlu5UFQA9PGB98kvTRx9jR/VnBIGW6mBYfgHdtJbT4EUQ5hJDGVFdOFTQ16Qktih65ThSEwkzWVgvmYnsTFZKheA49KJQtq9rNAFO83FuwIc0XpJljTVGzYxrwYj4TFhDfW9eNYoSaoOa9sb0RKlqUHtQu6C3l7YU5yizb6WBNmBT+aBKycN3N1fBwS03PFuvn9c3j4Xd4Ov+7HiDVOv3aU6dafUEUe398YDjsQEQnOilzmd4Lo+XWe2jY01q6yfFjUQsBQlVYHtfJ3JkWYkEapRdc1aenC55gJz3LUtNhCCW4Ewgji/kWuz8aJR4Sunix0LqwimpqlygQKQ1g==
    admin-user: AgCLZtloayozg4X+1GuNH/AnBokrtXZ+9AEVL64Cpx3SJyS1HXJqirA7FMlSFa7yiLmC32zmIkK76+W7IpE8YQasu9h3rhVNL3RrMottGIuFOKIsthlV66VIB9QXPKj+21FduDBdIOwIxJd/LCDr7rLeQ88ml11F9+69QDY8iygcGH9MWFvU0DSWv7a3ZBOy/rwUWQP7XbFHCSkzZDT18yzHY00D08WrX7ALJfh3ha1hb2lCNycG3/xqeZ9rgbE9pYk1oXTXpyxd1gGEIV4NuCMGYhnpHV9erdW7oFxUI5x+x6nf4S9wWao0wggsSU8eGGoih4X4lSA1Cf2+ZLgagGvkZdKVul/B/ZEwr+ww6va0OMNsn6vWY+TOF0rnmcBmhRg/7PaAY6Iw9BiHDN00fJMlkyXFXVomCOSzYkX56a58CsKkhq5jhcmq25wqJb3V2MAJGzIGcZ26Sp/BkI32al6o4cRUZfTBE1ujGJJcoKFxBSXYI9uhXPR/8YzbFTg++YZjJvUvPrtqFmPBBvzGwx6mnqm3xJjLk6YYyqw75QgHbEU3ominJKHIBTpUP3VzZ1w77o6FVRM1seYeCOwzf0Xa9TmNkCKPdbxOU9/DUsWsByKINDr6jtp6OKi7ZwAjIvNPttM+GUu6JvnqdH0Psx1e336Dr2Xehe+16/hLSm4U9V8IvnJWWWswCj+oDm6nxxphyl17uA==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
    type: Opaque
