apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-config 
  namespace: infra-system
data:
  config.yaml: |
    ingress:
      - hostname: "*.lab-hc.cloud"
        service: "http://traefik.kube-system.svc.cluster.local:80"
    
      - hostname: "lab-hc.cloud"
        service: "http://traefik.kube-system.svc.cluster.local:80"

      - service: "http_status:404"