---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: infra-system
spec:
  encryptedData:
    tunnel-token: AgCtLSfW28km0ms4AlTMwntZdVZ8V5b8yrcYtMqUyNPeSNNJaWkiSRUdj17T8fYrcEcWPi0aWESqi20Bw6VfiPrywKHmuohnmm2gFmkGuetzHYqITz5F51cCT9qpVw44f6RAF+gHIqHVt2xGcfcDlVdtdbazA3XLaSCbgXhtvQYXiDbvj7iHsm2V0UtmKFAbytS18QKs94Fx8bhpEhx+7Lj94wtyEBxSS1Ffk/e0d/NRPke4LVQq45I3N1ZxsFgfY1emBTQA2E4j81umWNeNz++0XMvtJ2wb/vhFda/UGL3gyX/V1PiEqk736hGqu8CaDcLeXLrFjkAn2c6vrC+XaxnENTHH0dJMbJSVZNL06DI6//tzr+qHRbLggnph8y/0DrZeOA/2VGLDKoXCI6MV3xlXvBdzKgZenSP0vbq5JZAbB8knT2YgBt4x/tiVuT78rNEs7XJ2DMEuaf7zPjgacoCGX8f6U4AD0OG58wM2IcR/DFDb943Lganz9k7NX7eUzOpkhbuq+SVVrB3kfM3qQonIZwi8QNrF15vu9VNuG6iqfYmuHDN6BpT5aSZrcfQDCMt9uGtXMoDOEKUmJozMKJ+MUre6PHzLoyGy3UHolaKsaDbsJZLSW3Wba9PY+9VtsKdKpQMyFA/Q9g6xosfRuNXxGWt7nGbyThkmx07lYPN6WnEbf/IW8BIXES+uPLeEy3Hbzg0gA+Al0tuNk+20Ma+2Tgq9gIq05a6KiLKWfL4fXA1legtnqwwwTPcSFBZxRZ9INS5s+1s2J6T5Sf7xi0tUIxNYWhZckMvX6zSARwgKt73gWFfrcGVJqoZCjs7zvxVVh55JafB1G7Y/bk4cKds+ZrJd8YnUs4pFxiyvteP6IeyInjnXfPWmzeFqmHfoVgTP6s1OIHSSrbwNxFpNnciLjCWRp/ZOobpI0TyBKHqlZaxzVSKry+X/
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: infra-system
    type: Opaque
