persistence:
  enabled: true
  existingClaim: grafana-pvc

admin:
  existingSecret: grafana-admin-creds
  userKey: admin-user
  passwordKey: admin-password

extraConfigmapMounts:
  - name: datasources
    mountPath: /etc/grafana/provisioning/datasources
    configMap: grafana-datasources
    readOnly: true
  - name: dashboards-provision
    mountPath: /etc/grafana/provisioning/dashboards
    configMap: grafana-dashboards-provision
    readOnly: true
  - name: dashboards
    mountPath: /var/lib/grafana/dashboards
    configMap: grafana-dashboards
    readOnly: true

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.lab-hc.cloud
