apiVersion: v1
kind: Namespace
metadata:
  name: infra-system
  labels:
    purpose: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    purpose: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-dev
  labels:
    purpose: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-prod
  labels:
    purpose: production
