---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: infra-system
spec:
  encryptedData:
    tunnel-token: AgAcigoXSWU60uU53Y5Uzd28itHJ3srRMeNlNsUcuMfJuaaqDrTmiqh9AoGV1/8PXUFor0SO01MA9gBo7LpAXy5JWQLtwE1n/DNIUCLpDKmghhnqEw5/ewp2EpVGuTye0IjozwcTGQX0OFmmQxGgFWc0RYwTuUGmbHJCNauMj7ps1mYcLSQPwI2Yi6c/3CHs/uEwerQRa7YGi9mb2rC2EjFAAulWg5/CZVucE/tzYTB0RoeFyky9MKs3MeTuhwhbu3nkqdS70iCGAuHUcW6avbwBGcNq2ZyT9Ak66qKP1uA2zZ3lxTAS59zYBisOa2VyHyPS2buOKvxXU2hmpi7kdprJHuP8UCB+312MmzcSFXScqfIPIuT7p7qCbhPkeSBX8+un1LzFey+bbCMSAAVmTiku1B5jJHmS6iaKWWGaWIVV2IDGsTxByQFjYouhWvIjUB/otxaTIwhzmNzNxZUqu8IOR81bkGGSHJp/I/vDSF8TbYJ/zDkpJNE2kBB70/UFHsSxEqd9zh0PHJqpZGbnEDU630q/KG7GWo/9Br7R6R7yAco4Ust6TbsVb56xy9Rvwfo4nvx99IMDYyHF8GIA/wMYhxwl2JykdlAlKjnQcZgeBNS1gccH8/IO7+P3bR5NecQcq7iJijh2+Z5NlOGzi99fcOpU/fKlQeqLeIJ9IynpOZmM/MMAhSwDZLjuOyJwxTm4nLgs/v4Zn6BPYrkKFSzE2tiMBSIrAq11mUpX/KyabwS/vOjNllVqWBfGQMg7qlIZNCMA8h7J5C89lh2qhWQxyceeQHyH526h2Bop4HAgJJJOc8rjF+0TBFqy52GlHxtta03hqULzrm7WNlN1CuWNUZpmkppXq0qBC6xeAEECnX+j5Z6G2h+AO9SIYCdglOYoDP/ZVuK9Ru2TtcOjTr7wzLx3T+xf4TYjn76LhkG/VMVJ0DYvFHqs
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: infra-system
    type: Opaque
